In [1]:
import numpy as np

In [12]:
 a = np.array([
     [1,2,3,4],
     [5,6,7,8],
     [9,10,11,12]])


In [13]:
a.shape #détermine la dimension de la matrice nxm

(3, 4)

In [15]:
a.ndim #Affiche le nombre des dimensions

2

In [16]:
a.dtype #type des données de la matrice

dtype('int32')

In [19]:
matriceUnitaire = np.ones((105, 60))
matriceUnitaire

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [20]:
matriceNulle = np.zeros((10, 6))
matriceNulle

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
matriceUniques = np.unique([1, 1, 2, 2, 3, 3])
matriceUniques

array([1, 2, 3])

In [26]:
matrice = np.array([[1, 0, 0],
                    [1, 0, 0],
                    [2, 3, 4]])
np.unique(matrice, axis = 0)

array([[1, 0, 0],
       [2, 3, 4]])

In [30]:
matrice = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
np.trim_zeros(matrice)

array([1, 2, 3, 0, 2, 1])